// xStock tokenized stocks by Backed Finance on Solana
// Each token is backed 1:1 by real shares held in custody
// Prices come from DexScreener/Jupiter (same as any SPL token)

export interface StockToken {
  symbol: string;       // e.g. 'TSLAx'
  stockSymbol: string;  // e.g. 'TSLA' (underlying stock ticker)
  name: string;         // e.g. 'Tesla xStock'
  companyName: string;  // e.g. 'Tesla'
  mint: string;         // Solana SPL token mint address
  logo: string;         // Company logo URL
  category: 'stock' | 'etf';
}

// Logo URLs from parqet (reliable, all stock symbols work)
const LOGO = (ticker: string) => `https://assets.parqet.com/logos/symbol/${ticker}`;

export const STOCK_TOKENS: StockToken[] = [
  // --- Major Indices / ETFs ---
  {
    symbol: 'SPYx',
    stockSymbol: 'SPY',
    name: 'SP500 xStock',
    companyName: 'S&P 500',
    mint: 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W',
    logo: LOGO('SPY'),
    category: 'etf',
  },
  {
    symbol: 'QQQx',
    stockSymbol: 'QQQ',
    name: 'Nasdaq xStock',
    companyName: 'Nasdaq 100',
    mint: 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ',
    logo: LOGO('QQQ'),
    category: 'etf',
  },
  {
    symbol: 'GLDx',
    stockSymbol: 'GLD',
    name: 'Gold xStock',
    companyName: 'Gold ETF',
    mint: 'Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re',
    logo: LOGO('GLD'),
    category: 'etf',
  },
  {
    symbol: 'TQQQx',
    stockSymbol: 'TQQQ',
    name: 'TQQQ xStock',
    companyName: 'Nasdaq 3x',
    mint: 'XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc',
    logo: LOGO('TQQQ'),
    category: 'etf',
  },
  {
    symbol: 'IWMx',
    stockSymbol: 'IWM',
    name: 'Russell 2000 xStock',
    companyName: 'Russell 2000',
    mint: 'XsbELVbLGBkn7xfMfyYuUipKGt1iRUc2B7pYRvFTFu3',
    logo: LOGO('IWM'),
    category: 'etf',
  },
  {
    symbol: 'VTIx',
    stockSymbol: 'VTI',
    name: 'Total Market xStock',
    companyName: 'Total Market',
    mint: 'XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9',
    logo: LOGO('VTI'),
    category: 'etf',
  },
  {
    symbol: 'IEMGx',
    stockSymbol: 'IEMG',
    name: 'Emerging Markets xStock',
    companyName: 'Emerging Mkts',
    mint: 'XsFnZawJdLdXfBSEt5Vw29K5vdBiHotdPLjUPafpfHs',
    logo: LOGO('IEMG'),
    category: 'etf',
  },
  {
    symbol: 'TBLLx',
    stockSymbol: 'TBLL',
    name: 'Treasury Bond xStock',
    companyName: 'US Treasury',
    mint: 'XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp',
    logo: LOGO('TBLL'),
    category: 'etf',
  },
  {
    symbol: 'SCHFx',
    stockSymbol: 'SCHF',
    name: 'Schwab Intl Equity xStock',
    companyName: 'Schwab Intl',
    mint: 'XsWAnFM77x6YvpdaZoos79R12o4Yj4r7EVkaTWddzhU',
    logo: LOGO('SCHF'),
    category: 'etf',
  },
  // --- Stocks ---
  {
    symbol: 'NVDAx',
    stockSymbol: 'NVDA',
    name: 'NVIDIA xStock',
    companyName: 'NVIDIA',
    mint: 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh',
    logo: LOGO('NVDA'),
    category: 'stock',
  },
  {
    symbol: 'AAPLx',
    stockSymbol: 'AAPL',
    name: 'Apple xStock',
    companyName: 'Apple',
    mint: 'XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp',
    logo: LOGO('AAPL'),
    category: 'stock',
  },
  {
    symbol: 'TSLAx',
    stockSymbol: 'TSLA',
    name: 'Tesla xStock',
    companyName: 'Tesla',
    mint: 'XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB',
    logo: LOGO('TSLA'),
    category: 'stock',
  },
  {
    symbol: 'GOOGLx',
    stockSymbol: 'GOOGL',
    name: 'Alphabet xStock',
    companyName: 'Google',
    mint: 'XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN',
    logo: LOGO('GOOGL'),
    category: 'stock',
  },
  {
    symbol: 'AMZNx',
    stockSymbol: 'AMZN',
    name: 'Amazon.com xStock',
    companyName: 'Amazon',
    mint: 'Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg',
    logo: LOGO('AMZN'),
    category: 'stock',
  },
  {
    symbol: 'METAx',
    stockSymbol: 'META',
    name: 'Meta xStock',
    companyName: 'Meta',
    mint: 'Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu',
    logo: LOGO('META'),
    category: 'stock',
  },
  {
    symbol: 'MSTRx',
    stockSymbol: 'MSTR',
    name: 'MicroStrategy xStock',
    companyName: 'MicroStrategy',
    mint: 'XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ',
    logo: LOGO('MSTR'),
    category: 'stock',
  },
  {
    symbol: 'COINx',
    stockSymbol: 'COIN',
    name: 'Coinbase xStock',
    companyName: 'Coinbase',
    mint: 'Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu',
    logo: LOGO('COIN'),
    category: 'stock',
  },
  {
    symbol: 'CRCLx',
    stockSymbol: 'CRCL',
    name: 'Circle xStock',
    companyName: 'Circle',
    mint: 'XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1',
    logo: LOGO('CRCL'),
    category: 'stock',
  },
  {
    symbol: 'HOODx',
    stockSymbol: 'HOOD',
    name: 'Robinhood xStock',
    companyName: 'Robinhood',
    mint: 'XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg',
    logo: LOGO('HOOD'),
    category: 'stock',
  },
  {
    symbol: 'MSFTx',
    stockSymbol: 'MSFT',
    name: 'Microsoft xStock',
    companyName: 'Microsoft',
    mint: 'XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX',
    logo: LOGO('MSFT'),
    category: 'stock',
  },
  {
    symbol: 'NFLXx',
    stockSymbol: 'NFLX',
    name: 'Netflix xStock',
    companyName: 'Netflix',
    mint: 'XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL',
    logo: LOGO('NFLX'),
    category: 'stock',
  },
  {
    symbol: 'ORCLx',
    stockSymbol: 'ORCL',
    name: 'Oracle xStock',
    companyName: 'Oracle',
    mint: 'XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL',
    logo: LOGO('ORCL'),
    category: 'stock',
  },
  {
    symbol: 'LLYx',
    stockSymbol: 'LLY',
    name: 'Eli Lilly xStock',
    companyName: 'Eli Lilly',
    mint: 'Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH',
    logo: LOGO('LLY'),
    category: 'stock',
  },
  {
    symbol: 'Vx',
    stockSymbol: 'V',
    name: 'Visa xStock',
    companyName: 'Visa',
    mint: 'XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p',
    logo: LOGO('V'),
    category: 'stock',
  },
  {
    symbol: 'BRK.Bx',
    stockSymbol: 'BRK.B',
    name: 'Berkshire xStock',
    companyName: 'Berkshire Hathaway',
    mint: 'Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x',
    logo: LOGO('BRK.B'),
    category: 'stock',
  },
  {
    symbol: 'UNHx',
    stockSymbol: 'UNH',
    name: 'UnitedHealth xStock',
    companyName: 'UnitedHealth',
    mint: 'XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe',
    logo: LOGO('UNH'),
    category: 'stock',
  },
  {
    symbol: 'KOx',
    stockSymbol: 'KO',
    name: 'Coca-Cola xStock',
    companyName: 'Coca-Cola',
    mint: 'XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ',
    logo: LOGO('KO'),
    category: 'stock',
  },
  {
    symbol: 'WMTx',
    stockSymbol: 'WMT',
    name: 'Walmart xStock',
    companyName: 'Walmart',
    mint: 'Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci',
    logo: LOGO('WMT'),
    category: 'stock',
  },
  {
    symbol: 'MCDx',
    stockSymbol: 'MCD',
    name: "McDonald's xStock",
    companyName: "McDonald's",
    mint: 'XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2',
    logo: LOGO('MCD'),
    category: 'stock',
  },
  {
    symbol: 'PGx',
    stockSymbol: 'PG',
    name: 'Procter & Gamble xStock',
    companyName: 'Procter & Gamble',
    mint: 'XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV',
    logo: LOGO('PG'),
    category: 'stock',
  },
  {
    symbol: 'CVXx',
    stockSymbol: 'CVX',
    name: 'Chevron xStock',
    companyName: 'Chevron',
    mint: 'XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts',
    logo: LOGO('CVX'),
    category: 'stock',
  },
  {
    symbol: 'AZNx',
    stockSymbol: 'AZN',
    name: 'AstraZeneca xStock',
    companyName: 'AstraZeneca',
    mint: 'Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU',
    logo: LOGO('AZN'),
    category: 'stock',
  },
  {
    symbol: 'GMEx',
    stockSymbol: 'GME',
    name: 'GameStop xStock',
    companyName: 'GameStop',
    mint: 'Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc',
    logo: LOGO('GME'),
    category: 'stock',
  },
  // --- Tech ---
  {
    symbol: 'AMDx',
    stockSymbol: 'AMD',
    name: 'AMD xStock',
    companyName: 'AMD',
    mint: 'XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF',
    logo: LOGO('AMD'),
    category: 'stock',
  },
  {
    symbol: 'AVGOx',
    stockSymbol: 'AVGO',
    name: 'Broadcom xStock',
    companyName: 'Broadcom',
    mint: 'XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo',
    logo: LOGO('AVGO'),
    category: 'stock',
  },
  {
    symbol: 'CRMx',
    stockSymbol: 'CRM',
    name: 'Salesforce xStock',
    companyName: 'Salesforce',
    mint: 'XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN',
    logo: LOGO('CRM'),
    category: 'stock',
  },
  {
    symbol: 'INTCx',
    stockSymbol: 'INTC',
    name: 'Intel xStock',
    companyName: 'Intel',
    mint: 'XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM',
    logo: LOGO('INTC'),
    category: 'stock',
  },
  {
    symbol: 'IBMx',
    stockSymbol: 'IBM',
    name: 'IBM xStock',
    companyName: 'IBM',
    mint: 'XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr',
    logo: LOGO('IBM'),
    category: 'stock',
  },
  {
    symbol: 'CRWDx',
    stockSymbol: 'CRWD',
    name: 'CrowdStrike xStock',
    companyName: 'CrowdStrike',
    mint: 'Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw',
    logo: LOGO('CRWD'),
    category: 'stock',
  },
  {
    symbol: 'APPx',
    stockSymbol: 'APP',
    name: 'AppLovin xStock',
    companyName: 'AppLovin',
    mint: 'XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV',
    logo: LOGO('APP'),
    category: 'stock',
  },
  {
    symbol: 'PLTRx',
    stockSymbol: 'PLTR',
    name: 'Palantir xStock',
    companyName: 'Palantir',
    mint: 'XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4',
    logo: LOGO('PLTR'),
    category: 'stock',
  },
  {
    symbol: 'CSCOx',
    stockSymbol: 'CSCO',
    name: 'Cisco xStock',
    companyName: 'Cisco',
    mint: 'Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf',
    logo: LOGO('CSCO'),
    category: 'stock',
  },
  {
    symbol: 'MRVLx',
    stockSymbol: 'MRVL',
    name: 'Marvell xStock',
    companyName: 'Marvell',
    mint: 'XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA',
    logo: LOGO('MRVL'),
    category: 'stock',
  },
  // --- Finance ---
  {
    symbol: 'JPMx',
    stockSymbol: 'JPM',
    name: 'JPMorgan xStock',
    companyName: 'JPMorgan',
    mint: 'XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C',
    logo: LOGO('JPM'),
    category: 'stock',
  },
  {
    symbol: 'GSx',
    stockSymbol: 'GS',
    name: 'Goldman Sachs xStock',
    companyName: 'Goldman Sachs',
    mint: 'XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1',
    logo: LOGO('GS'),
    category: 'stock',
  },
  {
    symbol: 'BACx',
    stockSymbol: 'BAC',
    name: 'Bank of America xStock',
    companyName: 'Bank of America',
    mint: 'XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP',
    logo: LOGO('BAC'),
    category: 'stock',
  },
  {
    symbol: 'MAx',
    stockSymbol: 'MA',
    name: 'Mastercard xStock',
    companyName: 'Mastercard',
    mint: 'XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC',
    logo: LOGO('MA'),
    category: 'stock',
  },
  // --- Healthcare ---
  {
    symbol: 'JNJx',
    stockSymbol: 'JNJ',
    name: 'Johnson & Johnson xStock',
    companyName: 'Johnson & Johnson',
    mint: 'XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn',
    logo: LOGO('JNJ'),
    category: 'stock',
  },
  {
    symbol: 'MRKx',
    stockSymbol: 'MRK',
    name: 'Merck xStock',
    companyName: 'Merck',
    mint: 'XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X',
    logo: LOGO('MRK'),
    category: 'stock',
  },
  {
    symbol: 'ABBVx',
    stockSymbol: 'ABBV',
    name: 'AbbVie xStock',
    companyName: 'AbbVie',
    mint: 'XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie',
    logo: LOGO('ABBV'),
    category: 'stock',
  },
  {
    symbol: 'PFEx',
    stockSymbol: 'PFE',
    name: 'Pfizer xStock',
    companyName: 'Pfizer',
    mint: 'XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw',
    logo: LOGO('PFE'),
    category: 'stock',
  },
  {
    symbol: 'NVOx',
    stockSymbol: 'NVO',
    name: 'Novo Nordisk xStock',
    companyName: 'Novo Nordisk',
    mint: 'XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n',
    logo: LOGO('NVO'),
    category: 'stock',
  },
  {
    symbol: 'TMOx',
    stockSymbol: 'TMO',
    name: 'Thermo Fisher xStock',
    companyName: 'Thermo Fisher',
    mint: 'Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57',
    logo: LOGO('TMO'),
    category: 'stock',
  },
  {
    symbol: 'DHRx',
    stockSymbol: 'DHR',
    name: 'Danaher xStock',
    companyName: 'Danaher',
    mint: 'Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV',
    logo: LOGO('DHR'),
    category: 'stock',
  },
  {
    symbol: 'MDTx',
    stockSymbol: 'MDT',
    name: 'Medtronic xStock',
    companyName: 'Medtronic',
    mint: 'XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2',
    logo: LOGO('MDT'),
    category: 'stock',
  },
  {
    symbol: 'ABTx',
    stockSymbol: 'ABT',
    name: 'Abbott xStock',
    companyName: 'Abbott',
    mint: 'XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7',
    logo: LOGO('ABT'),
    category: 'stock',
  },
  // --- Consumer / Industrial ---
  {
    symbol: 'PEPx',
    stockSymbol: 'PEP',
    name: 'PepsiCo xStock',
    companyName: 'PepsiCo',
    mint: 'Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF',
    logo: LOGO('PEP'),
    category: 'stock',
  },
  {
    symbol: 'HDx',
    stockSymbol: 'HD',
    name: 'Home Depot xStock',
    companyName: 'Home Depot',
    mint: 'XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3',
    logo: LOGO('HD'),
    category: 'stock',
  },
  {
    symbol: 'PMx',
    stockSymbol: 'PM',
    name: 'Philip Morris xStock',
    companyName: 'Philip Morris',
    mint: 'Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3',
    logo: LOGO('PM'),
    category: 'stock',
  },
  {
    symbol: 'LINx',
    stockSymbol: 'LIN',
    name: 'Linde xStock',
    companyName: 'Linde',
    mint: 'XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z',
    logo: LOGO('LIN'),
    category: 'stock',
  },
  {
    symbol: 'HONx',
    stockSymbol: 'HON',
    name: 'Honeywell xStock',
    companyName: 'Honeywell',
    mint: 'XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2',
    logo: LOGO('HON'),
    category: 'stock',
  },
  {
    symbol: 'ACNx',
    stockSymbol: 'ACN',
    name: 'Accenture xStock',
    companyName: 'Accenture',
    mint: 'Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU',
    logo: LOGO('ACN'),
    category: 'stock',
  },
  {
    symbol: 'CMCSAx',
    stockSymbol: 'CMCSA',
    name: 'Comcast xStock',
    companyName: 'Comcast',
    mint: 'XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8',
    logo: LOGO('CMCSA'),
    category: 'stock',
  },
  {
    symbol: 'OPENx',
    stockSymbol: 'OPEN',
    name: 'Opendoor xStock',
    companyName: 'Opendoor',
    mint: 'XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6',
    logo: LOGO('OPEN'),
    category: 'stock',
  },
  // --- Energy ---
  {
    symbol: 'XOMx',
    stockSymbol: 'XOM',
    name: 'Exxon Mobil xStock',
    companyName: 'Exxon Mobil',
    mint: 'XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh',
    logo: LOGO('XOM'),
    category: 'stock',
  },
  // --- Crypto / Other ---
  {
    symbol: 'DFDVx',
    stockSymbol: 'DFDV',
    name: 'DeFi Dev Corp xStock',
    companyName: 'DeFi Dev Corp',
    mint: 'Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy',
    logo: LOGO('DFDV'),
    category: 'stock',
  },
  {
    symbol: 'AMBRx',
    stockSymbol: 'AMBR',
    name: 'Amber xStock',
    companyName: 'Amber Intl',
    mint: 'XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb',
    logo: LOGO('AMBR'),
    category: 'stock',
  },
  {
    symbol: 'BMNRx',
    stockSymbol: 'BMNR',
    name: 'Bitmine xStock',
    companyName: 'Bitmine',
    mint: 'XsrBCwaH8c46xiqXBChzobgufRKxQxAWUWbndgBNzFn',
    logo: LOGO('BMNR'),
    category: 'stock',
  },
];

// Lookup helpers
export const STOCK_BY_MINT = new Map(STOCK_TOKENS.map(t => [t.mint, t]));
export const STOCK_BY_SYMBOL = new Map(STOCK_TOKENS.map(t => [t.symbol, t]));

// Get ETFs and stocks separately
export const INDEX_ETFS = STOCK_TOKENS.filter(t => t.category === 'etf');
export const STOCKS_ONLY = STOCK_TOKENS.filter(t => t.category === 'stock');
